John Doe, Programming Assignment 3, Algorithms 605.621

# Statement of Academic Integrity

Statement of Integrity: I, Derek Zhu, state that I completed this assignment with integrity and by myself.

# Instructions to Students
This programming assignment is contained entirely in this IPython/Jupyter notebook. You are to read the problem from this notebook, and answer questions/make required modifications in this same notebook and submit it as a notebook.  Look for **BOLDFACE AND/OR ALL CAPS** for where to put your answers.  Do not delete the problem statements, text, etc, leave all that as-is (makes grading easier).

# Overview

You are consulting for a group of people (who would prefer not to be mentioned here by name) whose job consists of monitoring and analyzing electronic signals coming from ships in the Atlantic ocean. They want a fast algorithm for _untangling_ a superposition of two known signals. You are to analyze an efficient algorithm that tells whether a signal s is a valid superposition of two known signals x and y, with x and y consisting of a common set of symbols, allowing for repeats of either x or y in s.

In this alternative assignment, you will investigate an algorithm that the instructor adapted significantly from an article from [Geeks for Geeks, Find if a string is interleaved of two other strings | DP-33](https://www.geeksforgeeks.org/find-if-a-string-is-interleaved-of-two-other-strings-dp-33/), as their original algorithm was presented without explanation.  (You may look at that if it helps.)  This is a useful example of _memoization,_ a technique that saves prior state computed on overlapping subproblems to avoid repetitive calculations.

# Algorithm
The following is the instructor's adapted algorithm.

<!--- This is a Markdown comment. -->
<!--- Separate the $...$ in many cases to get Latex to render properly.
      In output LaTeX, use incorrectly closed <span hidden> to pass in LaTeX options. -->
1. **function** isInterleaved(inA, inB, inS):
1. $~~~~$ A, B, S = inA, inB, inS
1. $~~~~$ m, n = len(A), len(B) _# A indexed by i, B indexed by j_

1. $~~~~$ A = "\_" $||$ A $~~~~$_#The underscore _ means the null symbol_
1. $~~~~$ B = "\_" $||$ B
1. $~~~~$ S = "\_" $||$ S

1. $~~~~$ TL $\gets$ _an m+1 by n+1 table of booleans all set to False initially_

1. $~~~~$ TL$_{0,\ 0} \gets$ True

1. $~~~~$ **for** i = 0 to m $~~~~$_# 0, 1, ... m-1, m_
1. $~~~~~~~~$ **for** j = 0 to n
1. $~~~~~~~~~~~~$ **if** i+j==0
1. $~~~~~~~~~~~~~~~~$ **continue** $~~~~$_# skip rest of this loop, continue w/next j_
1. $~~~~~~~~~~~~$ R$_a$, R$_b$ $\gets$ False
1. $~~~~~~~~~~~~$ **if** A$_i$ == S$_{i+j}$ **and** i $\ge$ 1
1. $~~~~~~~~~~~~~~~~$ R$_a$ $\gets$ TL$_{i-1,\ j}$
1. $~~~~~~~~~~~~$ **if** B$_j$ == S$_{i+j}$ **and** j $\ge$ 1
1. $~~~~~~~~~~~~~~~~$ R$_b$ $\gets$ TL$_{i,\ j-1}$
1. $~~~~~~~~~~~~$ TL$_{i,\ j} \gets$ R$_a$ **or** R$_b$
1. $~~~~~~~~$ **end for**
1. $~~~~$ **end for**
1. $~~~~$ **if** TL$_{m,\ n}$ == True
1. $~~~~~~~~$ **return** 1, 1
1. $~~~~$ **else**
1. $~~~~~~~~$ **return** False
1. **end function**

This algorithm accepts two collections of symbols inA and inB, called _strings_, and a third string inS that claims to be the output of an interleaving of the symbols of inA with those of inB.  The algorithm returns the count of the repetitions of A and B if inS is such an interleaving, else false.  It runs in O(mn) time.

***Note that*** the same signal is guaranteed not to interleave with itself.  If A is transmitting abc as its signal, it may be received as abcabcabc, but it will never be aabaccbcc.

For those new to programming, the _continue_ statement "bails out" and jumps to the next iteration.  In a _for_ loop, this means set the index to the next value and run the loop again.  Recall that $||$ means concatenation such that ``"h" || "ello"`` $\rightarrow$ ``"hello"``.

In [247]:
print_log = False
show_trace = False
def isInterleaved_no_leading_noise(inA, inB, inS):
    """
    Checks if S is an interleaving of strings A and B.  Returns the count
    (a, b) of the number of instances of A and B, respectively (at least 1,1).

    Adapted by R. Fink from Geeks for Geeks,
    https://www.geeksforgeeks.org/find-if-a-string-is-interleaved-of-two-other-strings-dp-33/

    Parameters
    ----------
    inA : string
    inB : string
    inS : string to check against

    Returns
    -------
    (int a, int b) count of a patterns and b patterns matched in S

    """
    ############################# begin My code
    total_a=0 # number repetitions of A
    total_b=0 # number repetitions of B
    isInterleaved = False
    if print_log:
      print()
      print("A=", end="")
      print(inA, end="")
      print(",B=", end="")
      print(inB, end="")
      print(",S=", end="")
      print(inS, )
    ############################# end My code

    A = inA
    B = inB
    S = inS

    m=len(A)            # A is down the rows, indexed by i, starting 1
    n=len(B)            # B goes across cols, indexed by j, starting 1
    l =len(S)
    if l==0 or m==0 or n==0:
      return (False, 0, 0)
    delta = l - (m+n)
    if delta <0:
      delta = 0
    else:
      for i in range(m, m+1 + delta):
        A = A+ A[i%m]
      for i in range(n, n+1 + delta):
        B = B+ B[i%n]


    # Add a dummy character at start, so that indexing starts at 1
    A = "*" + A         # _ represents the null character
    B = "*" + B
    S = "*" + S

    # Initialize the table;
    TL=[[False]*(n+1+delta) for _ in range(m+1+delta)] # initialize m x n table to false
    TL[0][0] = True             # represents null,null case (always true)

    tabstr_head =[x for x in B] # for printing



############################# begin: just print, nothing else
    if print_log:
      print(" ", end="")
      print(tabstr_head)
############################# end print

    tabstr=[["F"]*(n+1+delta) for _ in range(m+1+delta)] # for printing
    tabstr[0][0] = "T"

    # For all symbols in A, traveling top to bottom down the rows
    for i in range(0,m+1+delta):
        # For all symbols in B, traveling left to right across the columns
        for j in range (0,n+1+delta):
            if i+j==0:
                continue            # skip element 0,0 (already true)
            Ra = Rb = False
            # If the horizontal pattern A matches the next symbol of S,
            if i + j < len(S) and A[i] == S[i+j] and i>=1:
                Ra = TL[i-1][j]     # then propagate the state across the row
            # If the vertical pattern B matches the next symbol of S,
            if  i + j < len(S) and B[j] == S[i+j] and j>=1:
                Rb = TL[i][j-1]     # then propagate the state down the column

            # Take the union of the two states
            TL[i][j] = Ra or Rb


            # Print the "from" state  ^ from down column, < from across row
            if Ra and Rb:
              tabstr[i][j] = "+" #+ S[i+j]
            elif Ra:
              tabstr[i][j] = "^" #+ A[i]
            elif Rb:
              tabstr[i][j] =  "<" #+ B[j]
            elif i + j < len(S):
              tabstr[i][j] = "F" # +  S[i+j]
            else:
              tabstr[i][j] = " "

############################# begin: just print, nothing else
        if print_log:
          print(A[i], end="")
          print(tabstr[i])
############################# end print

    index_a = 0
    index_b = 0
    i= m+delta
    while i>0 and total_a==0:
      j= n+delta
      while j>0:
        if i%m==0 and (tabstr[i][j] == "+" or tabstr[i][j] == "^"):
          index_a = i
          break
        j = j - 1
      i = i - 1

    j= n+delta
    while j>0 and total_b==0:
      i= m+delta
      while i>0:
        if j%n==0 and (tabstr[i][j] == "+" or tabstr[i][j] == "<"):
          index_b = j
          break
        i = i - 1
      j = j - 1


    (a,b) = (index_a, index_b)
    if m>0:
      a = index_a//m
    if n>0:
      b = index_b//n

    if a>0 and b>0 and (a*m + b*n) == l:
      isInterleaved = True
    elif a>0 and b>0 and index_a>=m and index_b>=n: # skip tail noise
      isInterleaved = True
############################# begin: just print, nothing else
      if print_log:
        if (a*m + b*n) < l:
          print("tail noise: ",end="")
          print(inS[a*m + b*n+1:])
############################# end print

############################# begin: just print, nothing else
    if print_log:
      print()
      print("index_a=", end="")
      print(index_a, end="")
      print(" index_b=", end="")
      print(index_b, end="")
      print(", A's=", end="")
      print(a, end="")
      print(" B's=", end="")
      print(b, end="")
      print(", isInterleaved=", end="")
      print(isInterleaved)
############################# end print

    return (isInterleaved, a, b)

def isInterleaved_may_have_leading_noise(inA, inB, inS):
    (isInterleaved, a, b) = (False, 0, 0)
    while len(inS) > 0:
      (isInterleaved, a, b) = isInterleaved_no_leading_noise(inA, inB, inS)
      if a==0 or b==0: # skip leading noise
############################# begin: just print, nothing else
        if print_log:
          print("found leading noise: ", end="")
          print(inS[0:1])
############################# end print
        inS = inS[1:]
      else:
        break

    return (isInterleaved, a, b)


# Problems

## Preliminaries - Trace Tables
We're going to build an understanding of this algorithm by tracing through some examples.

For each one of these traces, construct a _trace table_ to store the value of TL as follows.  

Each entry in the trace table will consist of these characters and their associated meanings:

* ***T*** $~~$ True
* ***F*** $~~$ False
* ***^*** $~~$ the value of the cell above (prev row)
* ***&lt;*** $~~$ the value of the cell to the left (prev column)
* ***+*** $~~$ the value of the cell above, logically ***or***'d with the value of the cell to the left

For an input pattern A of length m, and B of length n, create a table with m+1 rows (going down) and n+1 columns (going across), all initialized to F.

Put pattern A down the left side, so that each symbol in A starts off a new row.  Put pattern B across the top, so that each symbol in B is the head of its own column.  Set the first two entries in both row, and column, to the * character as a placeholder for the null symbol.

## Example
Here is an example trace table, showing a run of "1001" on patterns A="101" and B="0". <br>
<br>

|||
|-|-|
| A:|  101 |
| B:|  0   |
|String:|  1001|

|        |  **\***   | **0**  |
|--------|-------|-------|
| **\*** |   T   |   F   |
| **1**  |   ^   |   <   |
| **0**  |   ^   |   +   |
| **1**  |   F   |   ^   |

(Copy the table code from this cell to supply your answers down below.  Show only completed tables, not iterative steps.)

We construct the table by placing A down the left, B across the top.  We also use splats (\*) as placeholders for the null character, as required in the algorithm.  Cells are indexed by row/column starting at 0,0, such that cell (1,0) is the second row, first column.  Per the algorithm, cell (0,0) is initialized to T (and all the rest are initialized to False).

To trace the algorithm, append a null character in front of the input signal string.  In our case, that makes S=N1001, where "N" is the null character.  Then, start at cell (1,0), where we consider the **1** from A (and nothing from B).  

Line 15 of the algorithm says that if A\[1\] matches the first symbol in S, then the current cell "inherits" the value from the cell above it, so we mark cell (1,0) with a **^**. (Note how the null character causes us to index our null-prefixed signal S\[0..\] starting from 1).

S=N<font color='red'>1</font>001

|        |  **\***   | **0**  |
|--------|-------|-------|
| **\*** |   T   |   F   |
| **1**  |   ^   |      |
| **0**  |      |      |
| **1**  |      |      |

Generally speaking, if S[i+j] matches:
 * A[i] but not B[j], then **^**
 * Not A[i] but B[j], then **<**
 * Both A[i] and B[j], then **+**
 * Neither A[i] nor B[j], then **F**

With these rules above, continuing down the row, cell (2,0) sees A\[2\]==0 matching S\[2\], so it inherits from above meaning we place a ^.  

S=N1<font color='red'>0</font>01

|        |  **\***   | **0**  |
|--------|-------|-------|
| **\*** |   T   |   F   |
| **1**  |   ^   |      |
| **0**  |   ^  |      |
| **1**  |      |      |

Finally, cell (3,0) does not see a match between A\[3\] and S\[3\], and \* from B can't match anything, so we place an **F**.  

S=N10<font color='red'>0</font>1

|        |  **\***   | **0**  |
|--------|-------|-------|
| **\*** |   T   |   F   |
| **1**  |   ^   |      |
| **0**  |   ^  |      |
| **1**  |   F   |      |

Now, move onto the second column (first character of B) and repeat the process above.  At cell (1,1), i and j add to two, so we look at S\[2\].  Since it matches B (per line 17), we indicate a left arrow.

S=N1<font color='red'>0</font>01

|        |  **\***   | **0**  |
|--------|-------|-------|
| **\*** |   T   |   F   |
| **1**  |   ^   |   <   |
| **0**  |   ^   |       |
| **1**  |   F   |       |

Note at cell (2,1), the 3rd actual character of S (which is 0) matches both the second character of A and the first character of B, so it gets a **+**.

S=N10<font color='red'>0</font>1

|        |  **\***   | **0**  |
|--------|-------|-------|
| **\*** |   T   |   F   |
| **1**  |   ^   |   <   |
| **0**  |   ^   |   +   |
| **1**  |   F   |       |

We proceed along until we complete the table as shown at the start.  We confirm the interleaving if and only if we can start at the last cell, and using the arrows and pluses, find a "path" back to a cell that encodes to True.  In this case, cell (3,2) evaluates to True if you can start at cell (3,2) and, following the arrows, find at least one path back to a cell with "T", cell (0,0) in this case.   In general, cell (m,n) will evaluate to True if and only if S is an interleaving of A and B.  

(Minor note - the algorithm itself assigns true/false to the table, not arrows and pluses.  The arrow/plus designation is to help us identify why each cell has a certain value, which is the beauty of the thing.)

**In your writeups and answers, PLEASE copy the Jupyter code for table at the top from this cell as a starting point for building your own trace table.  Do not show intermediate steps, just a final table.**




In [248]:
# Here is an example trace table, showing a run of "1001" on patterns A="101" and B="0".
print_log = True
A="101"
B="0"
S="1001"
r=isInterleaved_may_have_leading_noise(A, B, S)
print_log=False


A=101,B=0,S=1001
 ['*', '0', '0']
*['T', 'F']
1['^', '<']
0['^', '+']
1['F', '^']

index_a=3 index_b=1, A's=1 B's=1, isInterleaved=True


## Problem 1 (10 total)
### Part 1.a (5 pts)
Trace the algorithm on S=10011 made of interleavings of single instances of A=101 and B=01.  Modify the following table to provide a trace:

***MY ANSWER***

||
|-|-|
| A:|  101  |
| B:|  01   |
|String:|  10011|

|       |   *   | **0** | **1** |
|-------|-------|-------|-------|
|   *   |   T   |   F   |   F   |
| **1** |   ^   |   <   |   F   |
| **0** |   ^   |   +   |   <   |
| **1** |   F   |   ^   |   +   |


In [249]:
print_log = True
A="101"
B="01"
S="10011"
r=isInterleaved_may_have_leading_noise(A, B, S)
print_log=False


A=101,B=01,S=10011
 ['*', '0', '1', '0']
*['T', 'F', 'F']
1['^', '<', 'F']
0['^', '+', '<']
1['F', '^', '+']

index_a=3 index_b=2, A's=1 B's=1, isInterleaved=True



How does your table compare with the example provided above?  Answer:

***MY ANSWER*** *italicized text*

*There is a path number difference of 1 between the two tables: three paths in the example provided, four paths in my table*

### Part 1.b (5 pts)
Trace S=10111 using A=101 and B=01. Is S a valid interleaving of A and B? Provide a trace table below, don't just provide an answer:

***MY ANSWER***

*S is not a valid interleaving of A and B*

|||
|-|-|
| A:|  101  |
| B:|  01   |
|String:|  10111|

|       |   *   | **0** | **1** |
|-------|-------|-------|-------|
|   *   |   T   |   F   |  F    |
| **1** |   ^   |   <   |  <    |
| **0** |   ^   |   F   |  F    |
| **1** |   ^   |   F   |  F    |

In [250]:
print_log=True
A="101"
B="01"
S="10111"
r=isInterleaved_may_have_leading_noise(A, B, S)
print_log=False


A=101,B=01,S=10111
 ['*', '0', '1', '0']
*['T', 'F', 'F']
1['^', '<', '<']
0['^', 'F', 'F']
1['^', 'F', 'F']

index_a=0 index_b=2, A's=0 B's=1, isInterleaved=False
found leading noise: 1

A=101,B=01,S=0111
 ['*', '0', '1']
*['T', '<', '<']
1['F', '^', '+']
0['F', 'F', 'F']
1['F', 'F', ' ']

index_a=0 index_b=2, A's=0 B's=1, isInterleaved=False
found leading noise: 0

A=101,B=01,S=111
 ['*', '0', '1']
*['T', 'F', 'F']
1['^', 'F', 'F']
0['F', 'F', ' ']
1['F', ' ', ' ']

index_a=0 index_b=0, A's=0 B's=0, isInterleaved=False
found leading noise: 1

A=101,B=01,S=11
 ['*', '0', '1']
*['T', 'F', 'F']
1['^', 'F', ' ']
0['F', ' ', ' ']
1[' ', ' ', ' ']

index_a=0 index_b=0, A's=0 B's=0, isInterleaved=False
found leading noise: 1

A=101,B=01,S=1
 ['*', '0', '1']
*['T', 'F', ' ']
1['^', ' ', ' ']
0[' ', ' ', ' ']
1[' ', ' ', ' ']

index_a=0 index_b=0, A's=0 B's=0, isInterleaved=False
found leading noise: 1


## Problem 2 (20 total)
The algorithm only handles a single interleaving of strings.  Can you come up with a way to handle _two_ interleavings of A, with a single interleaving of B?

### Part 2.a (5 pts)
Consider original patterns from problem 1, where A=101 and B=01.  Consider string S=10011011 that has two copies of A instead of one.  Given the algorithm above, what is your strategy for successfully processing this string?  Answer:

***MY ANSWER***

###  Part 2.b (5 pts)
Provide a trace of your solution.  Copy/paste the table format from other cells.

***MY TRACE***

In [251]:
print_log=True
A="101"
B="01"
S="10011011"
r=isInterleaved_may_have_leading_noise(A, B, S)
print_log=False


A=101,B=01,S=10011011
 ['*', '0', '1', '0', '1', '0', '1']
*['T', 'F', 'F', 'F', 'F', 'F']
1['^', '<', 'F', 'F', 'F', 'F']
0['^', '+', '<', 'F', 'F', 'F']
1['F', '^', '+', '<', '<', 'F']
1['F', '^', 'F', '^', '+', ' ']
0['F', '^', '<', 'F', ' ', ' ']
1['F', '^', '+', ' ', ' ', ' ']
tail noise: 11

index_a=3 index_b=2, A's=1 B's=1, isInterleaved=True


### Part 2.c (10 pts)
Can your solution for handling 2 A's and 1 B also handle the simpler case of a single A and a single B?  Specifically, what part of your trace table for A=101, B=01, that solves S=10011011, might show a match on S=10011 using a single A and a single B?  Explain how.  (HINT: you might need to try 2 A's and 2 B's to see a pattern.)

***MY ANSWER and explaining how***

In [252]:
print_log=True
A="101"
B="01"
S="10011"
r=isInterleaved_may_have_leading_noise(A, B, S)

print("---------------------")

A="101"
B="01"
S="10011011"
r=isInterleaved_may_have_leading_noise(A, B, S)

print_log=False


A=101,B=01,S=10011
 ['*', '0', '1', '0']
*['T', 'F', 'F']
1['^', '<', 'F']
0['^', '+', '<']
1['F', '^', '+']

index_a=3 index_b=2, A's=1 B's=1, isInterleaved=True
---------------------

A=101,B=01,S=10011011
 ['*', '0', '1', '0', '1', '0', '1']
*['T', 'F', 'F', 'F', 'F', 'F']
1['^', '<', 'F', 'F', 'F', 'F']
0['^', '+', '<', 'F', 'F', 'F']
1['F', '^', '+', '<', '<', 'F']
1['F', '^', 'F', '^', '+', ' ']
0['F', '^', '<', 'F', ' ', ' ']
1['F', '^', '+', ' ', ' ', ' ']
tail noise: 11

index_a=3 index_b=2, A's=1 B's=1, isInterleaved=True


Remember your thinking, you'll apply it on [the final problem down below](#Problem-4-(40-total)).

## Problem 3 (30 total)
How do you handle initial / leading noise?  

The customer tells you that the signal S that they picked up may consist of noise at the beginning and at the end.  This is likely because they are running a capture during a live communications session, and cannot witness either the beginning or the end of the stream.  The noise may consist of parts of A or B, or parts of some other signal.  The point is, you don't want to "fail" a signal just because of leading noise.

### Part 3.a (10 pts)
Provide a strategy for handling leading noise.  Say specifically how to adjust the algorithm above to tolerate symbols and fragments that might come at the beginning of a valid interleaving S.

**MY STRATEGY:  Use sufficient detail.  For example: wrap lines xxx to yyy in a while loop that does zzz**

### Part 3.b (20 pts)
Now, modify the Python code below to implement your algorithm.  Clearly comment where your changes are.  Note that as is, the algorithm returns false. _The instructor will replace your strings and input with their own to test your code._

In [253]:
def isInterleaved(inA, inB, inS):
    (isInterleaved,a,b) = isInterleaved_may_have_leading_noise(inA, inB, inS)
    if isInterleaved==False:
      return False
    return (1,1)

### Part 3 Test Block

In [254]:
print_log=True
test_case_idx = 0
allpass=True

test_case_idx += 1
A="101"
B="01"
S="010011" # a "0" as leading noise
r=isInterleaved(A,B,S)
res=r==(1,1) ; allpass &= res
print(f"Test {test_case_idx}: didpass={res}, actual result={r}, expected result=(1,1), S=_{S}")


A=101,B=01,S=010011
 ['*', '0', '1', '0', '1']
*['T', '<', '<', '<']
1['F', '^', 'F', 'F']
0['F', '^', 'F', 'F']
1['F', 'F', 'F', 'F']
1['F', 'F', 'F', ' ']

index_a=0 index_b=0, A's=0 B's=0, isInterleaved=False
found leading noise: 0

A=101,B=01,S=10011
 ['*', '0', '1', '0']
*['T', 'F', 'F']
1['^', '<', 'F']
0['^', '+', '<']
1['F', '^', '+']

index_a=3 index_b=2, A's=1 B's=1, isInterleaved=True
Test 1: didpass=True, actual result=(1, 1), expected result=(1,1), S=_010011


In [255]:
# Test Block (no leading noise) - should see "didpass=True" for all of these.
# Should return (1,1) indicating A and B interleave in S
print_log=False
test_case_idx = 0
allpass=True

test_case_idx += 1
A="101"
B="01"
S="10011"
r=isInterleaved(A,B,S)
res=r==(1,1) ; allpass &= res # the (1,1) is the correct ans
print(f"Test {test_case_idx}: didpass={res}, actual result={r}, expected result=(1,1), S=_{S}")

# Should discard the leading 0 and return (1,1)
test_case_idx += 1
S="010011" # a "0" as leading noise
r=isInterleaved(A,B,S)
res=r==(1,1) ; allpass &= res
print(f"Test {test_case_idx}: didpass={res}, actual result={r}, expected result=(1,1), S=_{S}")

test_case_idx += 1
S="00000010011" # more leading noise, (1,1)
r=isInterleaved(A,B,S)
res=r==(1,1) ; allpass &= res
print(f"Test {test_case_idx}: didpass={res}, actual result={r}, expected result=(1,1), S=_{S}")

test_case_idx += 1
S="11111" # nothing but noise - False
r=isInterleaved(A,B,S)
res=r==False ; allpass &= res # we expect False here
print(f"Test {test_case_idx}: didpass={res}, actual result={r},  expected result=False, S=_{S}")

# Harder cases - the supplied PA3 implementation will throw errors; you must fix
res=False # default value
try:
  test_case_idx += 1
  S="111" # nothing but noise and a short signal
  r=isInterleaved(A,B,S)
  res=r==False ; allpass &= res
  print(f"Test {test_case_idx}: didpass={res}, actual result={r},  expected result=False, S=_{S}")

  # Should tolerate missing one of A or B and return False
  test_case_idx += 1
  S="101" # missing B
  r=isInterleaved(A,"",S)
  res=r==False ; allpass &= res
  print(f"Test {test_case_idx}: didpass={res}, actual result={r},  expected result=False, S=_{S}")

  # Should tolerate missing one of A or B and return False
  test_case_idx += 1
  S="01" # missing A
  r=isInterleaved("",B,S)
  res=r==False ; allpass &= res
  print(f"Test {test_case_idx}: didpass={res}, actual result={r},  expected result=False, S=_{S}")
except:
  print("Test {test_case_idx}: caught exception")
  allpass = False

# Final tally
print(f"\n{['FAILED ONE OR MORE TESTS', 'passed all tests'][allpass]}")


Test 1: didpass=True, actual result=(1, 1), expected result=(1,1), S=_10011
Test 2: didpass=True, actual result=(1, 1), expected result=(1,1), S=_010011
Test 3: didpass=True, actual result=(1, 1), expected result=(1,1), S=_00000010011
Test 4: didpass=True, actual result=False,  expected result=False, S=_11111
Test 5: didpass=True, actual result=False,  expected result=False, S=_111
Test 6: didpass=True, actual result=False,  expected result=False, S=_101
Test 7: didpass=True, actual result=False,  expected result=False, S=_01

passed all tests


## Problem 4 (40 total)

### Part 4.a (10 pts)
Building on your insights from [the problem about matching repetitions](#Problem-2-(20-total)), come up with a strategy for modifying the algorithm at the top to handle matching repetitions, and to count the maximum number of matched repetitions and return it.  Right now, the algorithm emits (1,1); if S is made of 3 instances of A interleaved with 2 instances of B, it should return the tuple (3,2).  


**MY STRATEGY:  Use sufficient detail.  For example: when lines xxx process a True, add code to lines yyy-zzz that does pppqqq**

### Part 4.b (5 pts)
Does your algorithm handle trailing noise (symbols that occur after the last valid match)?  If so, how?  Briefly describe:

***MY BRIEF DESCRIPTION***

### Part 4.c (5 pts)
Is this an example of bottom-up memoization or top-down memoization?  Why?  Also, briefly describe the repeated subproblems as part of memoization.  (Review the book - good description of this).

***MY ANSWER*** .. this is (bottom-up | top-down) memoization, because ... and the repeated subproblems are ... I don't need to write a lot, just enough.

### Part 4.d (20 pts)
Copy your Python code from above that handles leading noise, and modify it to return a count of the maximal matches of A and B per your algorithm.  Important! Change the name of your function to isInterleaved2.  Clearly comment where your changes are.

Note that without your repetition-detecting and noise-eliminating modifications, the algorithm returns (1,1) on the first string S, and False on the other two strings noiseS and badS.  With your modifications to handle both leading noise and repetitions, the output should be (3, 2), (2, 1) and False.  These are test data for you to use; the instructor will replace your strings and input with their own to test your code, so please try other combinations yourself.

In [256]:
## My Modified Code Goes Here - actual code, not pseudocode.  No pseudocode for this question.
def isInterleaved2(inA, inB, inS):
    (isInterleaved,a,b) = isInterleaved_may_have_leading_noise(inA, inB, inS)
    if isInterleaved==True:
      return (a,b)
    return False

### Part 4 Test Block

In [257]:
print_log=True
allpass2=True
A="101"
B="01"
test_case_idx = 3
S="10000111011" # invalid regardless of checking for noise and/or reps
r=isInterleaved2(A,B,S)
res=r==False ; allpass2 &= res
print(f"Test {test_case_idx}: didpass={res}, S={S}, actual answer={r}, expected answer: False")




A=101,B=01,S=10000111011
 ['*', '0', '1', '0', '1', '0', '1', '0', '1', '0']
*['T', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
1['^', '<', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
0['^', '+', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
1['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
1['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', ' ']
0['F', 'F', 'F', 'F', 'F', 'F', 'F', ' ', ' ']
1['F', 'F', 'F', 'F', 'F', 'F', ' ', ' ', ' ']
1['F', 'F', 'F', 'F', 'F', ' ', ' ', ' ', ' ']
0['F', 'F', 'F', 'F', ' ', ' ', ' ', ' ', ' ']
1['F', 'F', 'F', ' ', ' ', ' ', ' ', ' ', ' ']

index_a=0 index_b=0, A's=0 B's=0, isInterleaved=False
found leading noise: 1

A=101,B=01,S=0000111011
 ['*', '0', '1', '0', '1', '0', '1', '0', '1']
*['T', '<', 'F', 'F', 'F', 'F', 'F', 'F']
1['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
0['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
1['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
1['F', 'F', 'F', 'F', 'F', 'F', 'F', ' ']
0['F', 'F', 'F', 'F', 'F', 'F', ' ', ' ']
1['F', 'F', 'F', 'F', 'F', ' ', ' ', ' ']
1['F', '

In [258]:
# Test Block (multiple reps) - should see "didpass=True" for all of these.

print_log=False
allpass2=True
test_case_idx = 0

#case = (A,B,S,expect,note)
TEST_CASES = [
    ("101", "01", "1001110110011", (3,2), "3 A's, 2 B's"),
    ("101", "01", "001101101", (2,2), "2 A's, 2 B's, w/leading noise"),
    ("101", "01", "10000111011", False, "invalid regardless of checking for noise and/or reps"),
    ("101", "01", "0000001001111111111", (1,1), "leading noise and trailing noise"),
    ("123", "45", "1243541523", (2,2), "2 A, 2 B"),
    ("123", "45", "xxxxxxxxxxxx1243512435xxxxxxxxxxxx", (2,2), "(2 A, 2 B) with leading noise and trail noise"),
]

for (A,B,S,expect,note) in TEST_CASES:
  test_case_idx += 1
  r=isInterleaved2(A,B,S)
  res=r==expect ; allpass2 &= res
  print(f"Test {test_case_idx}: didpass={res}, S={S}, actual={r}, expected={expect}, note: {note}")

# Final tally
print(f"\n{['FAILED ONE OR MORE TESTS', 'passed all tests'][allpass2]}")


Test 1: didpass=False, S=1001110110011, actual=(1, 1), expected=(3, 2), note: 3 A's, 2 B's
Test 2: didpass=False, S=001101101, actual=(1, 1), expected=(2, 2), note: 2 A's, 2 B's, w/leading noise
Test 3: didpass=True, S=10000111011, actual=False, expected=False, note: invalid regardless of checking for noise and/or reps
Test 4: didpass=True, S=0000001001111111111, actual=(1, 1), expected=(1, 1), note: leading noise and trailing noise
Test 5: didpass=False, S=1243541523, actual=(1, 1), expected=(2, 2), note: 2 A, 2 B
Test 6: didpass=False, S=xxxxxxxxxxxx1243512435xxxxxxxxxxxx, actual=(1, 1), expected=(2, 2), note: (2 A, 2 B) with leading noise and trail noise

FAILED ONE OR MORE TESTS


## Final Thoughts

If you have any comments on this assignment, feel free to edit thisi block and write them here.  (This part is not being graded.)